### ISSUE TITLE
Issue on first load

### ISSUE THREAD

**Issue by tmartin8080** [DisruptiveAngels/administrate-field-refile#1]
Hey, thanks for the gem.  

Just curious if you've seen this issue after added a refile field to a dashboard:

```
LoadError: cannot load such file -- administrate/field/base
```

**Comment by acrogenesis** [comment]
hmm I think it has to do with your `administrate` version. Which version are you running? I'm running 0.1.4

**Comment by tmartin8080** [comment]
I am using the master branch of the gem which is probably an issue.

**Comment by acrogenesis** [comment]
I've update to the master branch and it's working fine. Could you copy me the full error log?

**Comment by tmartin8080** [comment]
It has to do with a separate custom field:

Turns out the error is coming from this file not your gem.

```
require "administrate/fields/base"

class PasswordField < Administrate::Field::Base
  def to_s
    data
  end
end
```

Do you have any other custom fields as well?

**Comment by acrogenesis** [comment]
I made a password field gem to https://github.com/DisruptiveAngels/administrate-field-password you can try that :+1:

**Comment by acrogenesis** [comment]
I'm closing the issue now, feel free to open it again. Thanks!
